### ISSUE TITLE
Using with npx server

### ISSUE THREAD

**Issue by liemkg1234** [sparfenyuk/mcp-proxy#56]
https://hub.docker.com/r/mcp/filesystem

i want to using filesystem, but it dont have in python uv. How can I use with npx?

**Comment by liemkg1234** [comment]
Hello @sparfenyuk, i want to run mcp-proxy at container:

# Docker compose:
```
  mcp-filesystem:
    build: mcp
    container_name: mcp-filesystem
    command: "--pass-environment --sse-port=8000 --sse-host 0.0.0.0 npx @modelcontextprotocol/server-filesystem /document"
    environment:
      - NPM_CONFIG_STRICT_SSL=false
    volumes:
      - ./volumes/mcp/document:/document
    restart: unless-stopped
    networks:
      - llm-lab
```

# Dockerfile

```
FROM ghcr.io/sparfenyuk/mcp-proxy:latest

RUN apk add --no-cache nodejs npm

RUN python3 -m ensurepip && pip install --no-cache-dir uv

ENV PATH="/usr/local/bin:$PATH" \
    UV_PYTHON_PREFERENCE=only-system

ENTRYPOINT [ "mcp-proxy" ]
```


and it supported 2 type: uv & npx package
